/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import javax.swing.JOptionPane;

/**
 *
 * @author fcast
 */
public class cantidadgruposUbi extends javax.swing.JFrame {

    /**
     * Creates new form cantidadgruposUbi
     */
    public cantidadgruposUbi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonde2ubi = new javax.swing.JButton();
        buttonde4ubi = new javax.swing.JButton();
        buttonde10ubi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buttonde2ubi.setBackground(new java.awt.Color(153, 255, 255));
        buttonde2ubi.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        buttonde2ubi.setText("2");
        buttonde2ubi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonde2ubiActionPerformed(evt);
            }
        });

        buttonde4ubi.setBackground(new java.awt.Color(153, 255, 255));
        buttonde4ubi.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        buttonde4ubi.setText("4");
        buttonde4ubi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonde4ubiActionPerformed(evt);
            }
        });

        buttonde10ubi.setBackground(new java.awt.Color(153, 255, 255));
        buttonde10ubi.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        buttonde10ubi.setText("10");
        buttonde10ubi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonde10ubiActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("Desea agrupar los estudiantes en grupos de:");

        jButton1.setBackground(new java.awt.Color(153, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jButton1.setText("volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 186, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonde10ubi)
                            .addComponent(buttonde4ubi, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonde2ubi, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addComponent(buttonde2ubi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonde4ubi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonde10ubi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void grupo2U(){
      
        if(true){
            
            
         JOptionPane.showMessageDialog(null, "los grupos se han creado y se han guardado en una carpeta como 2Ubi y se han guardado en un archivo txt");
                  
        }
        else{
                       
            
        }        
    }
    
    public void grupo4U(){
      
        if(true){
            
            
         JOptionPane.showMessageDialog(null, "los grupos se han creado y se han guardado en una carpeta como 4ubi y se han guardado en un archivo txt");
                  
        }
        else{
                       
            
        }        
    }
    
    public void grupo10U(){
      
        if(true){
            
            
         JOptionPane.showMessageDialog(null, "los grupos se han creado y se han guardado en una carpeta como 10ubi y se han guardado en un archivo txt");
                  
        }
        else{
                       
            
        }        
    }
    
    private void buttonde2ubiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonde2ubiActionPerformed
         grupo2U();
      gruposleer form=new gruposleer(); 
         form.setVisible(true);
       this.dispose(); 
    }//GEN-LAST:event_buttonde2ubiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       AGRUPACIONES form=new AGRUPACIONES(); 
         form.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void buttonde4ubiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonde4ubiActionPerformed
         grupo4U();
      gruposleer form=new gruposleer(); 
         form.setVisible(true);
       this.dispose(); 
    }//GEN-LAST:event_buttonde4ubiActionPerformed

    private void buttonde10ubiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonde10ubiActionPerformed
          grupo10U();
      gruposleer form=new gruposleer(); 
         form.setVisible(true);
       this.dispose(); 
    }//GEN-LAST:event_buttonde10ubiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cantidadgruposUbi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cantidadgruposUbi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cantidadgruposUbi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cantidadgruposUbi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cantidadgruposUbi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonde10ubi;
    private javax.swing.JButton buttonde2ubi;
    private javax.swing.JButton buttonde4ubi;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
