/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import javax.swing.JOptionPane;

/**
 *
 * @author fcast
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
     
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        texuser = new javax.swing.JLabel();
        passwordtex = new javax.swing.JLabel();
        userfield = new javax.swing.JTextField();
        passwordfield = new javax.swing.JPasswordField();
        buttonlogin = new javax.swing.JButton();
        buttonHandbook = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 3, 56)); // NOI18N
        jLabel1.setText("Bienvenido ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -20, 230, 129));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logos/teacher.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 141, 80));

        jLabel4.setFont(new java.awt.Font("Yu Gothic", 3, 18)); // NOI18N
        jLabel4.setText("Inicie sesión");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 119, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 160));

        texuser.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        texuser.setText("Digite su nombre de usuario: ");
        jPanel1.add(texuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 218, -1, -1));

        passwordtex.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        passwordtex.setText("Digite su contraseña:");
        jPanel1.add(passwordtex, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 336, 262, -1));

        userfield.setBackground(new java.awt.Color(102, 255, 255));
        userfield.setBorder(null);
        jPanel1.add(userfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 370, 20));

        passwordfield.setBackground(new java.awt.Color(102, 255, 255));
        passwordfield.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel1.add(passwordfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 373, -1));

        buttonlogin.setBackground(new java.awt.Color(153, 255, 255));
        buttonlogin.setText("Iniciar Sesión");
        buttonlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonloginActionPerformed(evt);
            }
        });
        jPanel1.add(buttonlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 458, -1, -1));

        buttonHandbook.setBackground(new java.awt.Color(153, 255, 255));
        buttonHandbook.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        buttonHandbook.setText("Manual de usuario ");
        buttonHandbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHandbookActionPerformed(evt);
            }
        });
        jPanel1.add(buttonHandbook, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 530, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 370, 10));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 370, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void sistema(){
      String user=userfield.getText();
      String password=String.valueOf(passwordfield.getPassword());
        if((user.equals("PABLITO"))&& (password.compareTo("12345678")==0)){
            
            
         JOptionPane.showMessageDialog(null, "Bienvenido al sistema");
         
         Sistema form=new Sistema(); 
         form.setVisible(true);
         this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(null, "Usuario incorrecto, vuelva intentarlo");
            
            passwordfield.setText("");
            userfield.setText(null);
            
        }        
    }
    
    
    private void buttonHandbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHandbookActionPerformed
        MANUAL form=new MANUAL(); 
         form.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_buttonHandbookActionPerformed

    private void buttonloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonloginActionPerformed
       sistema();
       
    }//GEN-LAST:event_buttonloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonHandbook;
    private javax.swing.JButton buttonlogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPasswordField passwordfield;
    private javax.swing.JLabel passwordtex;
    private javax.swing.JLabel texuser;
    private javax.swing.JTextField userfield;
    // End of variables declaration//GEN-END:variables
}
